### ISSUE TITLE
MVPレビュー依頼

### ISSUE THREAD

**Issue by takeda-chiaki-53b** [takeda-chiaki-53b/LeatherPalette#110]
## 各種情報
サービス名：LeatherPalette（レザーパレット）
Gitリポジトリ：https://github.com/takeda-chiaki-53b/LeatherPalette
サービスURL：https://graduation-app.onrender.com
（Renderは無料枠で契約中の為、１回目のアクセス時はサーバーがスリープ状態でタイムアウトになる場合があります。お手数ですが、その場合は再アクセスをお願いします。）

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- [x]  レスポンシブ対応
  

【認証・セッション管理関連】
- [x] ユーザー登録機能
- [x] ログイン、ログアウト機能
- [ ] パスワードリセット機能（ログイン不要）

【ログイン不要】
- 投稿検索、閲覧機能
  - [ ] フリーワード検索
  - [ ] 絞り込み検索（ブランド、カテゴリー、商品名、使用年数）
  - [x]  投稿詳細表示

【ログイン必須】
- マイページ機能
   - [ ]  お気に入り一覧機能
   - [x]  投稿一覧機能
- 投稿機能
    - 作成機能(以下フォームの予定内容)
        - [x]  写真
        - [x]  商品情報(ブランド)
        - [ ]  商品情報(カテゴリ、商品名、カラー)
        - [ ]  使用年数
        - [ ]  メンテナンス方法
        - [ ]  容量
  - [ ]  公開、非公開設定機能
  - [ ]  下書き保存機能
  - [ ]  投稿プレビュー表示機能
  - [x]  編集機能
  - [x]  削除機能

【adminマイページ内】→brand_admin権限に変更
- [x]  商品情報登録機能

## READMEレビュー時から変更した機能
■変更点： 
 - [x]  投稿一覧機能 はログイン不要にしました。
 
■開発途中でMVPリリース時点で作らなくなった機能：
写真の投稿機能がメインの為、以下は本リリースへ回しました。
【認証・セッション管理関連】
- [ ] パスワードリセット機能（ログイン不要）

【ログイン不要】
- 投稿検索、閲覧機能
  - [ ] フリーワード検索
  - [ ] 絞り込み検索（ブランド、カテゴリー、商品名、使用年数）

【ログイン必須】
- マイページ機能
   - [ ]  お気に入り一覧機能
- 投稿機能
    - 作成機能(投稿フォームの内容)
        - [ ]  商品情報(カテゴリ、商品名、カラー)
        - [ ]  使用年数
        - [ ]  メンテナンス方法
        - [ ]  容量
- [ ]  公開、非公開設定機能
- [ ]  下書き保存機能
- [ ]  投稿プレビュー表示機能

■追加した機能：
【ログイン必須】
- 投稿機能
    - 作成機能(投稿フォームの内容)
      - [x]  商品情報(ブランド)の選択機能

【brand_adminマイページ内】
- [x] 商品情報編集機能
- [x] 商品削除機能

## サービスイメージがわかるようなスクリーンショット等

| 投稿一覧、詳細閲覧(ログイン不要) |  
| ---- | 
| [![Image from Gyazo](https://i.gyazo.com/edcfba3f2e5cbc3ddba420d96c2fa263.gif)](https://gyazo.com/edcfba3f2e5cbc3ddba420d96c2fa263) | 

| 新規登録 |  ログイン |
| ---- | ---- |
|![Image](https://github.com/user-attachments/assets/b2fc5974-46be-4029-a90b-82d69a4b9ebf) | ![Image](https://github.com/user-attachments/assets/f97027e7-1df6-491c-93c4-70aa762f92dd) | 

| ログアウト| ログアウト後はトップへ遷移 |
| ---- | ---- |
| ![Image](https://github.com/user-attachments/assets/acbcc4a2-54b0-40cd-bc14-be2cfa784050) |  ![Image](https://github.com/user-attachments/assets/7c264af8-de12-47e9-8845-5b3892fe8e14) |

| 投稿作成 |  編集 | 削除 |
| ---- | ---- | ---- |
| ![Image](https://github.com/user-attachments/assets/e4aa69c1-48de-45d5-b2a2-2f66671da988) | ![Image](https://github.com/user-attachments/assets/d2f229e6-fd6a-4963-8d42-d828305dcbdf) | ![Image](https://github.com/user-attachments/assets/e0f98d15-26d4-486e-9d8f-60f1f4b9616f) |

| ブランドアカウント(brand_admin権限付与)の新規登録入口 |  ブランドアカウント新規登録画面 | 
| ---- |  ---- |
| トップ画面の「新規登録」押下後、以下のボタンが入口 | 専用画面へ切り替わりこのページから登録すると権限が付与される |
| ![Image](https://github.com/user-attachments/assets/c43b373e-b9d8-42ff-9cb7-93adbc79e76b) | ![Image](https://github.com/user-attachments/assets/60a0b7a1-4fce-43bd-9aca-f17bec3a1852) | 

| ブランドアカウント_マイページ |  ブランドアカウント_商品一覧 | 
| ---- | ---- | 
| ![Image](https://github.com/user-attachments/assets/45bd8393-c1af-476d-9ead-bdf54ba98ebf) | ![Image](https://github.com/user-attachments/assets/e7ca9d0a-712f-4166-b2e3-df0c4e824529) |

| ブランドアカウント_商品登録 | ブランドアカウント_商品編集 | ブランドアカウント_商品削除 |  
| ---- | ---- | ---- |
| ![Image](https://github.com/user-attachments/assets/dad8d127-30b8-4835-b044-64cdcb314261) | ![Image](https://github.com/user-attachments/assets/8c461708-d148-4063-9df5-649f1b131d94) | ![Image](https://github.com/user-attachments/assets/b647e87d-6308-4164-8ded-601147b328a4) |

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下も取り組む =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。

**Comment by takeda-chiaki-53b** [comment]
ありがとうございます！本リリースまで引き続き頑張ります！
こちらのissueはクローズさせていただきます。
